name: mis2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_svg: ^2.0.6
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_messaging: 16.0.4
  flutter_local_notifications: 17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
